language: r
dist: xenial
cache:
  packages: yes

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" PATH=$HOME/bin:$PATH

repos:
  XRAN: https://xran.yihui.org

before_script:
  - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"
  - R CMD INSTALL .
  - Rscript -e "blogdown::install_hugo(); blogdown::hugo_version()"

jobs:
  include:
    - r: oldrel
    - r: release
      before_cache:
        - Rscript -e 'xfun::pkg_load2("covr")'
      after_success:
        - Rscript -e 'covr::codecov()'
        - "(curl -L https://xran.yihui.org/r-xran | bash)"
    - r: devel
