language: r
dist: xenial
addons:
  snaps:
    - hugo
cache:
  packages: yes

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" PATH=$HOME/bin:$PATH

repos:
  XRAN: https://xran.yihui.org

before_script:
  - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"
  - Rscript -e 'xfun::pkg_load2(c("covr", "xml2"))'
  - hugo version

after_success:
  - Rscript -e 'covr::codecov()'
  - "(curl -L https://xran.yihui.org/r-xran | bash)"
