# Advanced Topics

## Different building methods {#methods}

If your website does not contain any Rmd files, it is very straightforward to render it --- just a system call to the `hugo` command. When your website contains Rmd files, **blogdown** has provided three different rendering methods to compile these Rmd files. A website can be built using the function `blogdown::build_site()`:

```{r eval=FALSE, code=formatR::usage(blogdown::build_site, output=FALSE), tidy=FALSE}
```

As mentioned in Section \@ref(global-options), the default value of the `method` argument is determined by the global option `blogdown.method`, and you can set this option in `.Rprofile`.

Both `html` and `html_encoded` use `rmarkdown::render()` to render Rmd files to HTML, and the technical differences between them are:

1. `method = 'html'` renders `*.Rmd` to `*.html`, and keeps the `*.html` output file under the same directory as `*.Rmd`; `method = 'html_encoded'` will move `*.html` to the directory `/blogdown/`.

1. An Rmd file may generate two directories for figures (`*_files/`) and cache (`*_cache/`), respectively, if you have plot output or HTML widgets [@R-htmlwidgets] in your R code chunks, or enabled the chunk option `cache = TRUE` for caching. In the figure directory, there will be a subdirectory `figure-html/` that contains your plot output files, and possibly other subdirectories containing HTML dependencies from HTML widgets (e.g., `jquery/`). For `method = 'html'`, it moves the figure directory to `/static/`, and the cache directory to `/blogdown/`. For `method = 'html_encoded'`, all output files and directories are moved to `/blogdown/`, including figures, cache, and `*.html`.

1. The name of the method `'html_encoded'` comes from the fact that the paths of R plot files and HTML widgets are first encoded in the `*.html` output, then Hugo is called to build the website, and finally all HTML files under the `/public/` directory are post-processed to decode the paths. The main reason for this trouble is that it is not easy to predict where a certain page will be rendered in the `/public/` directory,^[For example, a source file `/content/about.md` may be rendered to `/public/about/index.html`, and `/content/post/2017-02-14-hello.Rmd` could be rendered to `/public/2017/02/14/hello/index.html` (the content of the post could also be used in `/public/categories/index.html`). It dependes on the rules for permanent links you set for Hugo.] so the relative paths of figures and widgets may fail to work after a site is rendered, and they need to be resolved by post-processing. By comparison, `method = 'html'` does not need post-processing due to the fact that the relative paths will be resolved to absolute paths at the pre-processing stage.

We must have successfully confused you now, but do not worry. You do not have to understand these technical details, unless you want to help us with hacking. For an average user, you only need to know the pros and cons of the two methods.

- For `method = 'html'`:

    - Your `/content/` directory may not be completely clean, since it also contains `*.html` files.
    
    - If you use HTML widgets in Rmd, the HTML pages may not conform to W3C standards,^[W3C stands for World Wide Web Consortium: https://www.w3.org. In case you are really curious: the problem with `method = 'html'` for HTML widgets is that CSS styles may be declared in the `<body>` tag.] but the widgets will be most likely to work well anyway.
    
    - If your website is supposed to be placed in a subdirectory under a domain name (e.g., `http://example.com/my-project/`) when it is published, you must use `relativeurls = true` in `config.toml`.
    
    - Besides these relatively minor disadvantages, the major advantage of `method = 'html'` is that your website is ready to be compiled by Hugo _alone_ after you have compiled it through **blogdown** once, because there is no need to use R or **blogdown** to post-process the website like `method = 'html_encoded'`. This advantage gives you the freedom to use deploying services like Netlify (Chapter \@ref(deployment)), where neither R nor **blogdown** is not available, but Hugo is. It is also much faster than `'html_encoded'.`

- For `method = 'html_encoded'`:

    - Your `/content/` directory is free of output files.
    
    - The HTML files under `/public/` should conform to standards.
    
    - There is no need to adjust the `relativeurls` option.
    
    - The disadvantages are: rendering the website is dependent on **blogdown** all the time, and it is relatively slow.^[It should not be too bad. Typically a website can be rendered in a few seconds.]

There is a caching mechanism in `build_site()` to speed up building your website: an Rmd file will not be recompiled when its `*.html` output file is newer (this test is done through comparing file modification times). If you want to force `build_site()` to recompile the Rmd file even if it is older than the HTML output, you need to delete the HTML output, or edit the Rmd file.

No matter which method you choose to use, `build_site()` will always look for an R script `/R/build.R` and execute it if it exists. This gives you the complete freedom to do anything you want for the website. For example, you can call `knitr::knit()` to compile Rmd to Markdown (`*.md`) in this R script instead of using `rmarkdown::render()`. This feature is designed for advanced users who are really familiar with the **knitr** package^[Honestly, it was originally designed for Yihui himself to build his own website, but he realized this feature could actually free users from Hugo. For example, it is possible to use Jekyll (another popular static site generator) with **blogdown**, too.] and Hugo or other static website generators (see Chapter \@ref(other-generators)).

For `method = 'custom'`, you are completely on your own and should be responsible for building the website using `/R/build.R`; `build_site()` will not call `rmarkdown::render()` or Hugo at all in this case.

The argument `local` of `build_site()` indicates whether you want to build the website for local preview or publishing. In the former mode (`local = TRUE`), a few Hugo options are temporarily changed when building the site:

- `baseurl` is set to `/`, which means the root URL is `/`, even if you have set it to another value like `http://example.com/` in `config.toml`. This is because we do not really want the URLs in our website to have the actual base URL when previewing the website locally (e.g., you may be offline and cannot connect to `http://example.com/`).

- Posts and pages with the options `draft: true` and/or `future: true` in the YAML metadata are always rendered, i.e., drafts and posts with future publication dates are rendered in the local preview mode.

In the latter mode (`local = FALSE`), no options are modified, and all your options set in `config.toml` and YAML metadata are respected.

The function `blogdown::serve_site()` calls `blogdown::build_site(local = TRUE)`. Even if the website generated by `serve_site()` under `/public/` is a functional website, we still recommend that you call `blogdown::build_site(local = FALSE)`^[You can omit `local = FALSE` since it is the default.] before you publish the `/public/` folder. If your drafts and future posts contain (time-)sensitive information, you are strongly recommended to delete the `/public/` directory before you rebuild the site for publishing every time, because Hugo never deletes it, and your sensitive information may be rendered by a certain `build_site(local = TRUE)` call last time and left in the directory. If the website is really important, and you need to make sure you absolutely will not screw up anything every time you publish it, put the `/public/` directory under version control, so you have a chance to see which files were changed before you publish the new site.

