check_config = function(config, f) {
  hint = function(...) message2(..., files = f)
  base = config[['baseurl']]
  if (is_example_url(base)) hint(
    'You should change the "baseurl" option in ', f, ' from ', base,
    ' to your actual domain; if you do not have a domain, set "baseurl" to "/"'
  )
  ignore = c('\\.Rmd$', '\\.Rmarkdown$', '_cache$', '\\.knit\\.md$', '\\.utf8\\.md$')
  if (is.null(s <- config[['ignoreFiles']])) hint(
    "You are recommended to set the 'ignoreFiles' field in ", f, ' to: ',
    xfun::tojson(ignore)
  ) else if (!all(ignore %in% s)) hint(
    "You are recommended to ignore more items in the 'ignoreFiles' field in ", f, ": ",
    gsub('^\\[|\\]$', '', xfun::tojson(I(setdiff(ignore, s))))
  )
  if ('_files$' %in% s) hint(
    "You are recommended to remove the item '_files$' in the 'ignoreFiles' field in ", f, '.'
  )
  if (is.null(s <- config$markup$goldmark$renderer$unsafe) && hugo_available('0.60')) {
    h = config$markup$defaultMarkdownHandler
    if (is.null(h) || h == 'goldmark') config_goldmark(f)
  }
  check_netlify(f)
  if (getOption('blogdown.check_html', TRUE)) check_garbage_html()
  config
}

is_example_url = function(url) {
  is.character(url) && grepl(
    '^https?://(www[.])?(example.(org|com)|replace-this-with-your-hugo-site.com)/?', url
  )
}

config_goldmark = function(f, silent = FALSE) {
  x = switch(
    xfun::file_ext(f),
    yaml = '
markup:
  goldmark:
    renderer:
      unsafe: true
',
    toml = '
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
'
  )
  if (is.null(x)) return()
  if (!silent) message(
    "You are recommended to set the option 'unsafe' to true for goldmark in '", f,
    "' (see https://github.com/rstudio/blogdown/issues/447 for more info). "
  )
  if (silent || yes_no("Do you want blogdown to automatically set it for you?")) {
    cat(x, file = f, append = TRUE)
  } else message(c(
    "To set the option manually, add the following settings to '", f, "':\n", x
  ))
}

check_netlify = function(cfg) {
  if (!file.exists(f <- 'netlify.toml') || !getOption('blogdown.check.netlify', TRUE))
    return()
  hint = function(...) message2(..., files = f)
  x = read_toml(f)
  v = x$context$production$environment$HUGO_VERSION
  if (is.null(v)) v = x$build$environment$HUGO_VERSION

  if (is.null(v)) hint(
    "You are recommended to specify the Hugo version in the file '", f, "'. ",
    "If you are not sure how to do it, see the help page ?blogdown::config_netlify."
  ) else if ((v2 <- hugo_version()) != v) hint(
    'Your local Hugo version is ', v2, ' but the Hugo version specified in the ',
    "'", f, "' file is ", v, '. You are recommended to use the same version ',
    'locally and on Netlify. You may either blogdown::install_hugo("', v, '") or ',
    'set HUGO_VERSION to ', v2, ' in ', f, '.'
  )

  if (!is.null(p1 <- x$build$publish)) {
    p2 = publish_dir(tmp = FALSE, default = NULL)
    if (p3 <- is.null(p2)) p2 = 'public'
    if (!identical(p2, gsub('/$', '', p1))) hint(
      "The 'publish' setting in '", f, "' is '", p1, "' but the 'publishDir' setting for ",
      "Hugo is '", p2, "' (", if (p3) "Hugo's default" else c("as set in ", cfg),
      '). We recommend that you set publish = "', p2, '" in ', f, '.'
    )
  }
}

check_garbage_html = function() {
  res = unlist(lapply(list_files(content_file(), '[.]html$'), function(f) {
    if (file.size(f) < 200000) return()
    x = readLines(f, n = 15)
    if (any(x == '<meta name="generator" content="pandoc" />')) return(f)
  }))
  if (length(res)) message2(
    'Detected .html files that might have been generated by clicking the Knit ',
    'button in RStudio with blogdown < v0.21 and you may want to delete them:\n\n',
    paste(' ', res, collapse = '\n'), '\n\nIf you believe this is a false alarm, ',
    'you may set options(blogdown.check.html = FALSE) in your .Rprofile.'
  )
}
